# In this notebook we'll use Tensorflow Fundamentals

* Introduction to Tensor
* Getting information from Tensor
* Manipulating Tensor
* Tensorflow and NumPy
* Using @tf.function ( a way to speed up your regular python function)
* Using GPUs with Tensorflow
* Excercise

In [2]:
# Import Tensorflow

import tensorflow as tf
print(tf.__version__)

2.10.0


In [5]:
#Create tensors using tf.constant()
scalar = tf.constant(8)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [6]:
#Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim


0

In [7]:
#Create the vector tensor
vector = tf.constant([8,8])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([8, 8])>

In [8]:
#check the dimension of the vector
vector.ndim

1

In [11]:
#create a matrix, that has more than one dimension
matrix = tf.constant([[10,7],[3,2]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  2]])>

In [10]:
#check the dimension of the matrix tensor
matrix.ndim

2

In [13]:
#Create another matrix 
matrix_1 = tf.constant([[10.,7.],
                       [3.,5.],
                       [20.,8.]], dtype=tf.float16)
matrix_1

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  5.],
       [20.,  8.]], dtype=float16)>

In [14]:
# Number of dimension of Matrix_1
matrix_1.ndim

2

In [19]:
# Create a tensor 
tensor_1 = tf.constant([[[1,2,3],[4,5,6]],
                           [[7,8,9],[10,11,12]],
                           [[13,14,15],[16,17,18]]])
tensor_1

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [20]:
# Tensor dimension 
tensor_1.ndim

3

In [21]:
tensor_1.shape

TensorShape([3, 2, 3])

# Create Tensor using the variable tf.variable()

In [24]:
changable_tensor = tf.Variable([5,7])
unchangable_tensor = tf.constant([5,7])
changable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 7])>)

In [28]:
#change one of the value in the changable tensor
changable_tensor[0].assign(10)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([10,  7])>

In [29]:
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>