In [6]:
import numpy as np

# Create a 1-dimensional NumPy array using np.array()


# Create a 2-dimensional NumPy array using np.array()


# Create a 3-dimensional Numpy array using np.array()

In [31]:
# 1- D Arrary
a1 = np.array([3,5,8,9])

In [32]:
# 2 - D Array
a2 = np.array([[2,4,6,8],[3,5,7,9]])

In [33]:
# 3 - D Array
a3 = np.array([[[3,4,5,6],[5,6,7,8]],
                 [[9,0,1,2],[3,4,5,6]],
                [[7,8,9,0],[1,2,3,4]]])


    np.array()
    np.ones()
    np.zeros()
    np.random.rand(5, 3)
    np.random.randint(10, size=5)
    np.random.seed() - pseudo random numbers
    Searching the documentation example (finding np.unique() and using it)


In [15]:
# Create a simple array
simple_array = np.array([1, 2, 3])
simple_array

array([1, 2, 3])

In [16]:
simple_array = np.array((4, 5, 6))
simple_array, simple_array.dtype

(array([4, 5, 6]), dtype('int32'))

In [17]:
np.random.rand(5, 3)

array([[0.46982939, 0.40920834, 0.65946464],
       [0.49851712, 0.36898598, 0.41069548],
       [0.01521316, 0.35057764, 0.99119256],
       [0.81727705, 0.27385004, 0.53961192],
       [0.27616366, 0.27334183, 0.48043132]])

In [18]:
np.random.randint(10, size=5)

array([7, 7, 8, 3, 6])

In [21]:
np.random.seed(0)

In [22]:
np.random.randint(10, size=(5, 3))

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

2-D random array size of [5,3]

In [26]:
np.random.random([5,3])

array([[0.97645947, 0.4686512 , 0.97676109],
       [0.60484552, 0.73926358, 0.03918779],
       [0.28280696, 0.12019656, 0.2961402 ],
       [0.11872772, 0.31798318, 0.41426299],
       [0.0641475 , 0.69247212, 0.56660145]])

3-D random array size of [5,3,2]

In [28]:
np.random.random([5,3,2])

array([[[0.61801543, 0.4287687 ],
        [0.13547406, 0.29828233],
        [0.56996491, 0.59087276]],

       [[0.57432525, 0.65320082],
        [0.65210327, 0.43141844],
        [0.8965466 , 0.36756187]],

       [[0.43586493, 0.89192336],
        [0.80619399, 0.70388858],
        [0.10022689, 0.91948261]],

       [[0.7142413 , 0.99884701],
        [0.1494483 , 0.86812606],
        [0.16249293, 0.61555956]],

       [[0.12381998, 0.84800823],
        [0.80731896, 0.56910074],
        [0.4071833 , 0.069167  ]]])

In [29]:
np.unique(np.random.random([5,3]))

array([0.01171408, 0.01852179, 0.05433799, 0.17162968, 0.19999652,
       0.35997806, 0.45354268, 0.52103661, 0.69742877, 0.7220556 ,
       0.72999056, 0.7936977 , 0.85580334, 0.86638233, 0.97552151])

In [34]:
a3[0]

array([[3, 4, 5, 6],
       [5, 6, 7, 8]])

In [39]:
a3[:3,:2,:2]

array([[[3, 4],
        [5, 6]],

       [[9, 0],
        [3, 4]],

       [[7, 8],
        [1, 2]]])

In [36]:
a3

array([[[3, 4, 5, 6],
        [5, 6, 7, 8]],

       [[9, 0, 1, 2],
        [3, 4, 5, 6]],

       [[7, 8, 9, 0],
        [1, 2, 3, 4]]])